name: hauberk
environment:
  sdk: '^2.10.0'
dependencies:
  malison: '^0.11.3'
  markdown: any
  path: any
  piecemeal: '^0.4.1'
dev_dependencies:
  build_runner: any
  build_web_compilers: any
  test: any