name: hauberk
environment:
  sdk: '^3.8.0'
dependencies:
  malison: '^0.13.2'
  markdown: any
  path: any
  piecemeal: '^2.0.0'
dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  lints: any
  test: any
